### ISSUE TITLE
Feature request: Pause/resume recording

### ISSUE THREAD

**Issue by strawb3rryx7** [omergul/LLSimpleCamera#85]
Kayıt yaparken, kayıdı pause moduna alıp, ardından tekrar resume edebilmek ve bunların aynı dosyada toplanıp çıktısı verilirse büyük bir eksiği kapanmış olur library'nin.

**Comment by InheritX** [comment]
Hi, 

There should be some way to pause - resume video recording.

Also there should be some way to continue recording if user changes front / rear camera while recording.

**Comment by ramonsgds** [comment]
ˆˆˆˆˆˆˆˆˆ EXACTLY. I really need switching camera position front/rear and rear/front.

**Comment by ramonsgds** [comment]
Though it seems that AVCaptureVideoDataOutput would be need for that, not AVCaptureMovieFileOutput, that is being currently used.

**Comment by souvickcse** [comment]
@ramonsgds How to use AVCaptureVideoDataOutput to do that?
